name: 'render content.md to pages'
on:
  push:
    branches:
      main
  
jobs:
  call-workflow:
    uses: eliamarcantognini/template-readable-text/.github/workflows/render-md-to-pages.yml@main
    secrets: inherit